// src/components/Contact.jsx
// Reads everything from src/data/personal.js
// DO NOT edit this file — edit personal.js only
//
// Features:
//  - Bio section
//  - Email + Phone contact cards (phone hidden if "")
//  - Social link buttons (driven by personal.socials array)
//  - Download CV button
//  - Footer with copyright

import { useRef, useEffect, useState } from "react";
import { personal } from "../data/personal";

// ── CONTACT CARD ──────────────────────────────────────────────────────────────
function ContactCard({ icon, label, value, href, accent }) {
  const [hovered, setHovered] = useState(false);

  return (
    <a
      href={href}
      target={href.startsWith("http") ? "_blank" : "_self"}
      rel="noreferrer"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: "flex", alignItems: "center", gap: 14,
        padding: "1.1rem 1.4rem",
        background: hovered ? "rgba(255,255,255,0.07)" : "rgba(255,255,255,0.04)",
        border: `0.5px solid ${hovered ? accent + "88" : "rgba(255,255,255,0.09)"}`,
        borderRadius: 14,
        textDecoration: "none",
        transition: "all .2s",
        transform: hovered ? "translateY(-3px)" : "translateY(0)",
      }}
    >
      {/* icon circle */}
      <div style={{
        width: 42, height: 42, borderRadius: "50%",
        background: `${accent}20`,
        border: `0.5px solid ${accent}44`,
        display: "flex", alignItems: "center", justifyContent: "center",
        fontSize: 18, flexShrink: 0,
      }}>
        {icon}
      </div>
      <div>
        <p style={{ fontSize: 11, color: "rgba(255,255,255,0.35)", margin: "0 0 2px", letterSpacing: "1px", textTransform: "uppercase" }}>
          {label}
        </p>
        <p style={{ fontSize: 14, fontWeight: 500, color: "#fff", margin: 0 }}>
          {value}
        </p>
      </div>
      {/* arrow */}
      <span style={{ marginLeft: "auto", color: accent, fontSize: 16, opacity: hovered ? 1 : 0.3, transition: "opacity .2s" }}>
        →
      </span>
    </a>
  );
}

// ── SOCIAL BUTTON ─────────────────────────────────────────────────────────────
function SocialBtn({ social }) {
  const [hovered, setHovered] = useState(false);
  return (
    <a
      href={social.url}
      target="_blank"
      rel="noreferrer"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: "inline-flex", alignItems: "center", gap: 8,
        padding: "9px 20px", borderRadius: 99,
        fontSize: 13, fontWeight: 500,
        fontFamily: "'DM Sans', sans-serif",
        textDecoration: "none",
        border: "0.5px solid",
        transition: "all .18s",
        background: hovered ? `${social.color}22` : "transparent",
        borderColor: hovered ? social.color : "rgba(255,255,255,0.18)",
        color: hovered ? social.color : "rgba(255,255,255,0.55)",
        transform: hovered ? "translateY(-2px)" : "translateY(0)",
      }}
    >
      {social.label} ↗
    </a>
  );
}

// ── MAIN SECTION ──────────────────────────────────────────────────────────────
export default function Contact() {
  const sectionRef            = useRef(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  // Build contact cards — hide phone if empty
  const contactCards = [
    {
      icon: "✉",
      label: "Email",
      value: personal.email,
      href: `mailto:${personal.email}`,
      accent: "#7F77DD",
    },
    personal.phone && {
      icon: "☏",
      label: "Phone",
      value: personal.phone,
      href: `tel:${personal.phone}`,
      accent: "#1D9E75",
    },
    {
      icon: "⌥",
      label: "GitHub",
      value: personal.github.replace("https://", ""),
      href: personal.github,
      accent: "#FAC775",
    },
    {
      icon: "in",
      label: "LinkedIn",
      value: personal.linkedin.replace("https://linkedin.com/in/", "@"),
      href: personal.linkedin,
      accent: "#378ADD",
    },
  ].filter(Boolean); // removes falsy entries (e.g. empty phone)

  return (
    <section
      id="contact"
      ref={sectionRef}
      style={{
        minHeight: "100vh",
        background: "#0a0a0a",
        padding: "6rem 2.5rem 0",
        position: "relative",
        overflow: "hidden",
        fontFamily: "'DM Sans', sans-serif",
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(24px)",
        transition: "opacity .6s ease, transform .6s ease",
      }}
    >
      {/* Background blobs */}
      <div style={{
        position: "absolute", borderRadius: "50%", pointerEvents: "none",
        width: 400, height: 400, background: "#7F77DD",
        top: -80, left: -100, opacity: 0.13, filter: "blur(80px)",
      }}/>
      <div style={{
        position: "absolute", borderRadius: "50%", pointerEvents: "none",
        width: 350, height: 350, background: "#1D9E75",
        bottom: 100, right: -80, opacity: 0.12, filter: "blur(80px)",
      }}/>

      <div style={{ maxWidth: 760, margin: "0 auto", position: "relative", zIndex: 10 }}>

        {/* Section label */}
        <p style={{
          fontSize: 11, letterSpacing: "3px", textTransform: "uppercase",
          color: "#7F77DD", marginBottom: 8, fontWeight: 500,
        }}>
          Get In Touch
        </p>

        {/* Heading */}
        <h2 style={{
          fontFamily: "'Syne', sans-serif",
          fontSize: "clamp(30px, 5vw, 52px)",
          fontWeight: 800, color: "#fff",
          letterSpacing: "-1.5px", marginBottom: 6,
        }}>
          Let's <span style={{ color: "#7F77DD" }}>Connect</span>
        </h2>
        <p style={{ fontSize: 15, color: "rgba(255,255,255,0.4)", marginBottom: "3rem" }}>
          Whether it's a project, opportunity, or just a hello — my inbox is always open.
        </p>

        {/* Bio card */}
        <div style={{
          background: "rgba(255,255,255,0.04)",
          border: "0.5px solid rgba(127,119,221,0.3)",
          borderRadius: 16, padding: "1.4rem 1.6rem",
          marginBottom: "2rem",
          position: "relative", overflow: "hidden",
        }}>
          <div style={{
            position: "absolute", top: 0, left: 0, right: 0, height: 2,
            background: "linear-gradient(90deg, #7F77DD, #1D9E75)",
            borderRadius: "16px 16px 0 0",
          }}/>
          {/* avatar + name row */}
          <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 14 }}>
            <div style={{
              width: 52, height: 52, borderRadius: "50%",
              background: "rgba(127,119,221,0.15)",
              border: "0.5px solid rgba(127,119,221,0.4)",
              display: "flex", alignItems: "center", justifyContent: "center",
              fontFamily: "'Syne', sans-serif", fontSize: 18,
              fontWeight: 800, color: "#7F77DD", flexShrink: 0,
            }}>
              {personal.initials}
            </div>
            <div>
              <p style={{ fontSize: 16, fontWeight: 600, color: "#fff", margin: 0 }}>
                {personal.name}
              </p>
              <p style={{ fontSize: 13, color: "rgba(255,255,255,0.4)", margin: 0 }}>
                {personal.role}
              </p>
            </div>
            {/* status badge */}
            <div style={{
              marginLeft: "auto",
              display: "inline-flex", alignItems: "center", gap: 6,
              background: "rgba(29,158,117,0.12)",
              border: "0.5px solid rgba(29,158,117,0.4)",
              color: "#5DCAA5", fontSize: 11, fontWeight: 500,
              padding: "4px 12px", borderRadius: 99,
            }}>
              <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#1D9E75", display: "inline-block" }}/>
              {personal.status}
            </div>
          </div>

          {/* bio text */}
          <p style={{
            fontSize: 14, color: "rgba(255,255,255,0.55)",
            lineHeight: 1.8, margin: 0,
          }}>
            {personal.bio}
          </p>
        </div>

        {/* Contact cards grid */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
          gap: 12, marginBottom: "2rem",
        }}>
          {contactCards.map((c) => (
            <ContactCard key={c.label} {...c} />
          ))}
        </div>

        {/* Social buttons row */}
        {personal.socials.length > 0 && (
          <div style={{ marginBottom: "2.5rem" }}>
            <p style={{
              fontSize: 11, letterSpacing: "2px", textTransform: "uppercase",
              color: "rgba(255,255,255,0.25)", marginBottom: "1rem", fontWeight: 500,
            }}>
              Find Me On
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}>
              {personal.socials.map((s) => (
                <SocialBtn key={s.label} social={s} />
              ))}
            </div>
          </div>
        )}

        {/* Download CV button */}
        <div style={{ marginBottom: "4rem" }}>
          <a
            href={personal.cvLink}
            download
            style={{
              display: "inline-flex", alignItems: "center", gap: 8,
              padding: "13px 30px", borderRadius: 10,
              fontSize: 14, fontWeight: 600,
              fontFamily: "'DM Sans', sans-serif",
              textDecoration: "none",
              background: "#7F77DD", color: "#fff",
              transition: "background .2s, transform .15s",
            }}
            onMouseOver={(e) => { e.currentTarget.style.background = "#534AB7"; e.currentTarget.style.transform = "translateY(-2px)"; }}
            onMouseOut={(e)  => { e.currentTarget.style.background = "#7F77DD"; e.currentTarget.style.transform = "translateY(0)"; }}
          >
            ↓ Download CV
          </a>
        </div>

      </div>

      {/* ── FOOTER ── */}
      <div style={{
        borderTop: "0.5px solid rgba(255,255,255,0.07)",
        padding: "1.5rem 2.5rem",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        flexWrap: "wrap",
        gap: 10,
      }}>
        <p style={{ fontSize: 13, color: "rgba(255,255,255,0.25)", margin: 0 }}>
          © {new Date().getFullYear()} {personal.name}. Built with React + Tailwind.
        </p>
        <p style={{ fontSize: 13, color: "rgba(255,255,255,0.2)", margin: 0 }}>
          Designed & developed by {personal.name.split(" ")[0]}
        </p>
      </div>

    </section>
  );
}