// src/components/Skills.jsx
// Reads everything from src/data/skills.js
// DO NOT edit this file to update skills — edit skills.js only

import { useState, useRef, useEffect } from "react";
import { skills } from "../data/skills";

const TABS = ["All", "Languages", "Tech Stack"];

// ── LANGUAGE PILL ─────────────────────────────────────────────────────────────
function LangPill({ s }) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "10px 16px",
        borderRadius: 12,
        background: s.bg,
        border: `0.5px solid ${s.border}`,
        cursor: "default",
        transition: "transform .18s",
      }}
      onMouseOver={(e) => (e.currentTarget.style.transform = "translateY(-3px)")}
      onMouseOut={(e)  => (e.currentTarget.style.transform = "translateY(0)")}
    >
      {/* icon badge */}
      <div
        style={{
          width: 34, height: 34,
          borderRadius: 8,
          background: s.bg,
          border: `0.5px solid ${s.border}`,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontFamily: "'Syne', sans-serif",
          fontWeight: 800, fontSize: 12,
          color: s.color,
          flexShrink: 0,
        }}
      >
        {s.icon}
      </div>
      <span style={{ fontSize: 14, fontWeight: 500, color: "#fff" }}>
        {s.name}
      </span>
    </div>
  );
}

// ── TECH GROUP CARD ───────────────────────────────────────────────────────────
function TechCard({ group }) {
  return (
    <div
      style={{
        background: "rgba(255,255,255,0.04)",
        border: `0.5px solid ${group.accent}44`,
        borderRadius: 16,
        padding: "1.3rem",
        transition: "transform .2s, border-color .2s",
      }}
      onMouseOver={(e) => {
        e.currentTarget.style.transform = "translateY(-4px)";
        e.currentTarget.style.borderColor = `${group.accent}99`;
      }}
      onMouseOut={(e) => {
        e.currentTarget.style.transform = "translateY(0)";
        e.currentTarget.style.borderColor = `${group.accent}44`;
      }}
    >
      {/* card header */}
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
        <div
          style={{
            width: 4, height: 20,
            background: group.accent,
            borderRadius: 99,
            flexShrink: 0,
          }}
        />
        <span style={{ fontSize: 14, fontWeight: 600, color: group.accent }}>
          {group.category}
        </span>
        <span style={{
          marginLeft: "auto",
          fontSize: 11,
          color: "rgba(255,255,255,0.25)",
          background: "rgba(255,255,255,0.05)",
          border: "0.5px solid rgba(255,255,255,0.1)",
          borderRadius: 99,
          padding: "2px 8px",
        }}>
          {group.items.length} skills
        </span>
      </div>

      {/* tech pills */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
        {group.items.map((item) => (
          <span
            key={item}
            style={{
              fontSize: 12, fontWeight: 500,
              padding: "5px 12px", borderRadius: 99,
              background: `${group.accent}18`,
              border: `0.5px solid ${group.accent}44`,
              color: "rgba(255,255,255,0.8)",
              transition: "transform .15s, background .15s",
              cursor: "default",
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.transform = "translateY(-2px)";
              e.currentTarget.style.background = `${group.accent}30`;
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.transform = "translateY(0)";
              e.currentTarget.style.background = `${group.accent}18`;
            }}
          >
            {item}
          </span>
        ))}
      </div>
    </div>
  );
}

// ── MAIN SECTION ──────────────────────────────────────────────────────────────
export default function Skills() {
  const [tab, setTab]         = useState("All");
  const sectionRef            = useRef(null);
  const [visible, setVisible] = useState(false);

  // Animate in when section scrolls into view
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.1 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  // Filter displayed categories
  const displayed =
    tab === "All"
      ? skills.tech
      : tab === "Tech Stack"
      ? skills.tech
      : [];

  const showLanguages = tab === "All" || tab === "Languages";
  const showTech      = tab === "All" || tab === "Tech Stack";

  // Quick stats
  const totalSkills =
    skills.languages.length +
    skills.tech.reduce((a, g) => a + g.items.length, 0);

  const quickStats = [
    { value: skills.languages.length,  label: "Languages",   color: "#FAC775" },
    { value: skills.tech.length,       label: "Tech Groups", color: "#7F77DD" },
    { value: totalSkills,              label: "Total Skills", color: "#1D9E75" },
  ];

  return (
    <section
      id="skills"
      ref={sectionRef}
      style={{
        minHeight: "100vh",
        background: "#0a0a0a",
        padding: "6rem 2.5rem 5rem",
        position: "relative",
        overflow: "hidden",
        fontFamily: "'DM Sans', sans-serif",
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(24px)",
        transition: "opacity .6s ease, transform .6s ease",
      }}
    >
      {/* Background blobs */}
      <div style={{
        position: "absolute", borderRadius: "50%", pointerEvents: "none",
        width: 400, height: 400, background: "#7F77DD",
        top: -100, left: -100, opacity: 0.13, filter: "blur(80px)",
      }}/>
      <div style={{
        position: "absolute", borderRadius: "50%", pointerEvents: "none",
        width: 300, height: 300, background: "#ED93B1",
        bottom: -60, right: -60, opacity: 0.12, filter: "blur(70px)",
      }}/>

      <div style={{ maxWidth: 960, margin: "0 auto", position: "relative", zIndex: 10 }}>

        {/* Section label */}
        <p style={{
          fontSize: 11, letterSpacing: "3px", textTransform: "uppercase",
          color: "#7F77DD", marginBottom: 8, fontWeight: 500,
        }}>
          What I Work With
        </p>

        {/* Heading */}
        <h2 style={{
          fontFamily: "'Syne', sans-serif",
          fontSize: "clamp(30px, 5vw, 52px)",
          fontWeight: 800, color: "#fff",
          letterSpacing: "-1.5px", marginBottom: 6,
        }}>
          My <span style={{ color: "#7F77DD" }}>Skills</span>
        </h2>
        <p style={{ fontSize: 15, color: "rgba(255,255,255,0.4)", marginBottom: "2.5rem" }}>
          Languages I speak and the tech stack I build with
        </p>

        {/* Quick stats */}
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginBottom: "2rem" }}>
          {quickStats.map((s) => (
            <div key={s.label} style={{
              display: "flex", alignItems: "center", gap: 10,
              background: "rgba(255,255,255,0.04)",
              border: "0.5px solid rgba(255,255,255,0.08)",
              borderRadius: 12, padding: "10px 18px",
            }}>
              <span style={{
                fontFamily: "'Syne', sans-serif",
                fontSize: 24, fontWeight: 800, color: s.color,
              }}>
                {s.value}
              </span>
              <span style={{ fontSize: 12, color: "rgba(255,255,255,0.35)" }}>
                {s.label}
              </span>
            </div>
          ))}
        </div>

        {/* Filter tabs */}
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: "2rem" }}>
          {TABS.map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              style={{
                padding: "7px 20px", borderRadius: 99,
                fontSize: 13, fontWeight: 500,
                fontFamily: "'DM Sans', sans-serif",
                border: "0.5px solid",
                cursor: "pointer",
                transition: "all .18s",
                background: tab === t ? "rgba(127,119,221,0.15)" : "transparent",
                borderColor: tab === t ? "#7F77DD" : "rgba(255,255,255,0.15)",
                color: tab === t ? "#AFA9EC" : "rgba(255,255,255,0.45)",
              }}
            >
              {t}
            </button>
          ))}
        </div>

        {/* ── Languages ── */}
        {showLanguages && (
          <div style={{ marginBottom: "2.5rem" }}>
            <p style={{
              fontSize: 11, letterSpacing: "2px", textTransform: "uppercase",
              color: "rgba(255,255,255,0.25)", marginBottom: "1rem", fontWeight: 500,
            }}>
              Programming Languages
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
              {skills.languages.map((s) => (
                <LangPill key={s.name} s={s} />
              ))}
            </div>
          </div>
        )}

        {/* Divider */}
        {tab === "All" && (
          <div style={{
            height: "0.5px",
            background: "rgba(255,255,255,0.07)",
            marginBottom: "2.5rem",
          }}/>
        )}

        {/* ── Tech Stack ── */}
        {showTech && (
          <div>
            <p style={{
              fontSize: 11, letterSpacing: "2px", textTransform: "uppercase",
              color: "rgba(255,255,255,0.25)", marginBottom: "1rem", fontWeight: 500,
            }}>
              Tech Stack
            </p>
            <div style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
              gap: 14,
            }}>
              {displayed.map((g) => (
                <TechCard key={g.category} group={g} />
              ))}
            </div>
          </div>
        )}

      </div>
    </section>
  );
}